apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosava-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prosava-web
  template:
    metadata:
      labels:
        app: prosava-web
    spec:
      containers:
      - name: prosava-web
        image: samuelkadima/sava:v1.0.0
        resources:
          limits:
            memory: "800Mi"
            cpu: "800m"
        ports:
        - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: prosava-service
spec:
  type: LoadBalancer
  selector:
    app: prosava-web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000

